name: association_psfdf
description: "A new Flutter project."

publish_to: 'none' 

version: 1.0.0+1

environment:
  sdk: ^3.6.0


dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.8
  font_awesome_flutter: ^10.5.0
  geolocator: ^9.0.1
  geocoding: ^2.0.0
  http: ^0.13.3
  intl: ^0.18.0
  googleapis: ^9.0.0
  googleapis_auth: ^1.0.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_launcher_icons: ^0.9.2
  flutter_lints: ^5.0.0
 

flutter:
  uses-material-design: true
  assets:
    - assets/icons/app_icon.png

flutter_launcher_icons:
  android: true
  ios: true
  image_path: "assets/icons/app_icon.png"